paths-ignore:
  - "freppledb/common/static/js/angular*.js"
  - "freppledb/common/static/js/*.src.js"
  - "freppledb/common/static/js/jquery.jqgrid.src.js"
  - "freppledb/common/static/js/d3.js"
  - "freppledb/common/static/js/bootstrap.js"
