name: "Code scanning"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["cpp", "javascript", "python"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - if: matrix.language != 'cpp'
        name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - if: matrix.language == 'cpp'
        name: Compile C++
        run: |
          sudo apt update
          sudo apt install libxerces-c-dev openssl libssl-dev libpq5 libpq-dev python3-dev
          sudo -H python3 -m pip install --upgrade pip
          sudo -H pip3 install -r "${{github.workspace}}/requirements.dev.txt"
          mkdir build
          cd build
          cmake ..
          cmake --build . -- -j 2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
