name: "Code scan"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '41 19 * * *'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-18.04
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp', 'javascript', 'python' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python packages
      uses: py-actions/py-dependency-install@v2
      with:
        path: "${{github.workspace}}/requirements.txt"

    - name: Install dependencies
      run: sudo apt-get install libxerces-c-dev openssl libssl-dev libpq5 libpq-dev

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
