name: "Code scanning"

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths-ignore:
      - "doc/**"
      - "*.md"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - "doc/**"

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["cpp", "javascript", "python"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          config-file: ./.github/code_scanning_config.yml
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.

          # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
          # queries: security-extended,security-and-quality

      - if: matrix.language != 'cpp'
        name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - if: matrix.language == 'cpp'
        name: Compile C++
        run: |
          sudo apt-get update
          sudo apt-get install libxerces-c-dev openssl libssl-dev libpq5 libpq-dev python3-dev
          mkdir build
          cd build
          cmake ..
          cmake --build . -- -j 2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
