name: Build Community

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: frepple
          POSTGRES_PASSWORD: frepple
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checking out source code
        uses: actions/checkout@v2

      - name: Set up Nodes
        uses: actions/setup-node@v2

      - name: Install packages
        run: |
          sudo apt-get install libxerces-c-dev openssl libssl-dev libpq5 libpq-dev postgresql-client python3 python3-dev python3-psycopg2 python3-setuptools
          npm install
          sudo -H python3 -m pip install --upgrade pip
          sudo -H pip3 install -r "${{github.workspace}}/requirements.dev.txt"

      - name: Build
        run: |
          grunt
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target package
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target doc

      - name: Test
        working-directory: ${{github.workspace}}
        run: |
          cp djangosettings.py djangosettings.original.py
          sed -i "s/\"HOST\":.\"\"/\"HOST\":\"localhost\"/g" djangosettings.py
          sed -i "s/\"PORT\":.\"\"/\"PORT\":\"${{ job.services.postgres.ports[5432] }}\"/g" djangosettings.py
          ./test/runtest.py --regression
          ./frepplectl.py test freppledb --verbosity=2
